# Machine Learning Nanodegree Capstone Project
# Music Genre Classification

## Problem Statement

The problem we are trying to address here is, Can machine Learn Genre of a song by analysing the various feature of songs. Can we match and/or break the break benchmark set by the benchmark model.

Based on the research paper <br>
_From Classical to Hip-hop: Can Machine Learn Genre? A student publication by Aaron kravitz,Eliza lupone, Ryan Diaz_

## Project Overview
Historically, attempts made by others to build music genre classification systems have yielded fine but not extraordinary results. Some who used the same dataset that we used for our project, which comprises one million songs each belonging to one of ten different genres, often chose to reduce the number of genres they attempted to identify, while those who decided to work with all ten genres only achieved accuracy of 40%. The hardest part of music classification is working with time series data. The cutting edge of machine learning research is looking into more effective ways of extracting features from time series data, but is still a long way off. The most promising attempt is done by Goroshin et. al in their paper Unsupervised Feature Learning from Temporal
Data. The problem with temporal data is that the number of features varies per each training example. This makes learning hard, and in particular makes it hard to extract information on exactly what the algorithm is using to “learn”. Algorithms that extract temporal features can be thought of as extracting a more reasonably sized set of
features that can be learned from. To address the difficulties of working with temporal data, we used the idea of an acoustic fingerprint to extract a constant sized number of features from each song, improving our accuracy on the testing set substantially.

## System Overview

Extracting feature from music file for classification is not that easy. Digital music is discretized sampled
waveform, although categorization over frequency domain is preferred than the time domain because
of the ability of humans to differentiate between frequencies range like, deep bass in hip-hop is Low
frequency while talking, singing is mid-range frequency and sharp claps are considered high-pitched
frequency.<br>
<br>
The base of the project is Million Songs genre dataset that initially contains songs with 34 summary
features given as ‘genre, track id, artist name, title, loudness, tempo, time signature, key, mode, duration
and 24 different timbre value for each segment’. Each of the song is categorized in one of the 10 genres,
mainly classic pop and rock, classical, dance and electronica, folk, pop, hip-hop, jazz and blues, punk,
metal & lastly soul and reggae. After that feature scaling has been applied over the dataset to obtain 30
summary feature namely ‘loudness, tempo, time signature, key, mode, duration and 24 different timbre
value for each segment’ along with the ‘genre’ for each song. The resultant dataset has been modified
3 into 9 genre collection by removing hip-hop. Before applying the machine learning algorithms over
dataset it has been accessed to obtain almost equal number of features for each genre (approx. 2000
songs of each genre) type so as to provide a good training condition for Multiclass Classification
algorithms. Some of the main classification algorithms applied are Decision Tree classifier, K Nearest
Neighbor classifier, Random Forest and Naïve Bayes classifier, out of which Random Forest has given
the best result of 62% F1-Score. The machine learning algorithm has been formulated using scikit learn
library and numpy library of python programming.<br><br>
Apart from that, the dataset has been modified into 2 summary feature dataset, one being genre and
other the lyrics of that particular song, for lyrical modelling approach to be applied over it. Based on
the availability of lyrics for each song in the ‘MSD’ dataset for only approx. 24700 songs has been
formed that has been re-featured to a collection of approx. 7500 songs in 8 genres. In Lyrical Model
the concept of ‘bag of words’ has been implemented for categorization.

## DataSets and Inputs

For this project the __Million Song Genre Dataset__ has been used, that is been made available by __LabROSA__ at Columbia university , for educational study purpose, Although we will be working with the subset that will be preprocessed by us.This dataset consists of about million songs of various genres, to be precise of 10 genres, namely classic pop and rock , classical , dance and electronica, folk, pop, hip-hop,
jazz and blues, punk, metal & lastly soul and reggae .The distribution of songs into various genres can be recognized in Dataset Composition. This dataset is a well-organized classification dataset as it consist the features of each of the song in the dataset too. The Million Song Dataset has about million songs with related metadata and audio analysis features, In this dataset, we have each song as a training example containing 34 summary features along with the genre of the track , which would be of use during training as well as testing the classifiers for predicting the genre of particular combination of features. 
<br>
The dataset contains various __features__ that needs little description.

- __genre__ : is the music category of the particular track in the dataset.
- __track_id__ : is the musicmatch track id of the track.
- __artist_name__ : is the song’s artist name.
- __title__ : title of the song.
- __loudness__ : is the property of a sound that is primarily a psychological correlation of physical strength (amplitude).
- __tempo__ : The tempo is the speed of the underlying beat for a piece of music. Tempo is measured in BPM, or Beats/Minute. The top number represents how many beats there are in a measure, and the bottom number represents the note value which makes one beat.
- __key__ : The key of a piece is a group of pitches, or scale upon which a music composition is created.
- __mode__ : Refers to a type of scale, coupled with a set of characteristic melodic behaviors.
- __duration__ : song duration (in Secs).
- __avg_timber1 - 12__ : Timbre is then a general term for the distinguishable characteristics of a tone.
- __var_timber1 – 12__ : Timbre is mainly determined by the harmonic content of a sound and the dynamic characteristics.

<br>
Apart from this, we will be using __Lyrical Modelling concept__ , i.e. to classify genre from the lyrics of the song. We will be collecting available lyrics from the internet and implementing bag of words approach on them.

For this we will be scraping lyrics from [Lyrics Wikia](http://lyrics.wikia.com/)


We get the preprocessed version of Million Song Dataset and get Million Song Genre Dataset
Which can be found and downloaded from this [link](https://labrosa.ee.columbia.edu/millionsong/blog/11-2-28-deriving-genre-dataset) 

### Loading Dataset and Inputs
Loading Million Song Genre Dataset, 
then taking 2000 samples at most from each available genre so that we get a balanced dataset.

Reasons for choosing 2000 samples from each categories:

1. This makes our dataset more balanced and doesn't favours one category over above.
2. This is done keeping in mind, system resource availability for Storage and Computation of input.


In the next block, we load the dataset and show you the composition of dataset. We had around 59000 songs that had genre information available about them. we chose and properly composed our dataset out of it. 

In [14]:
#load and save the dataset and features
#Features in extracted from genre_dataset
#####################################################################
'''
Features                        Features Description 


genre,                          Genre of the song
track_id,                       Musicmatch track_id
artist_name,                    Artist of the song
title,                          Title of the song
loudness,                       Loudness is the characteristic of a sound that is primarily a psychological correlate of physical strength (amplitude).
tempo,                          The tempo of a piece of music is the speed of the underlying beat. Tempo is measured in BPM, or Beats Per Minute.
time_signature,                 The top number represents how many beats there are in a measure, and the bottom number represents the note value which makes one beat.
key,                            The key of a piece is a group of pitches, or scale upon which a music composition is created.	
mode,                           Refers to a type of scale, coupled with a set of characteristic melodic behaviours. 
duration,                       song duration (in Secs)
avg_timbre1,                    Timbre is then a general term for the distinguishable characteristics of a tone.
avg_timbre2,                    Timbre is mainly determined by the harmonic content of a sound 
avg_timbre3,                    and the dynamic characteristics.
avg_timbre4,
avg_timbre5,
avg_timbre6,
avg_timbre7,
avg_timbre8,
avg_timbre9,
avg_timbre10,
avg_timbre11,
avg_timbre12,
var_timbre1,
var_timbre2,
var_timbre3,
var_timbre4,
var_timbre5,
var_timbre6,
var_timbre7,
var_timbre8,
var_timbre9,
var_timbre10,
var_timbre11,
var_timbre12
'''
######################################################################################





######################################################################################
#                               ABOUT FILE
#
#File Contains code for Extracting Information from the "msd_genre_dataset.txt" file
#that contains all the features and labels that will be helpful in 
#predicting genres.
######################################################################################



######################################################################################
#
#                     Library Import Statements
#
#
######################################################################################

import numpy as np
import math
import sys
import matplotlib
import time
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
######################################################################################
#
#                              HELPER FUNCTIONS
#
######################################################################################



def processItem(datapoint):
    info=[datapoint[0]]
    for feature in datapoint[4:]:
        info.append(float(feature))
    return info



data_list=[]

genres=["jazz and blues","classic pop and rock","classical","punk","metal","pop","dance and electronica","hip-hop","soul and reggae","folk"]
def preprocess():
    #open msd_genre_dataset.txt in read mode

    line_num=0  #line number in text file
    #################################################################
    '''
    Steps
    1. skip 10 lines as no useful data is there.
    2. Now, Read line by line and store that info in appropriate data structure for further analysis 
    '''
    ############################################################
    '''
    The with statement handles opening and closing the file, 
    including if an exception is raised in the inner block. 
    The for line in f treats the file object f as an iterable, 
    which automatically uses buffered IO and memory management 
    so you don't have to worry about large files.
    '''
    ############################################################
    genres={}

    with open('msd_genre_dataset.txt','r') as f:
        for line in f:
            if line_num<10:
                pass
            else:
                temp=line.split(',')
                try:
                    if(genres[temp[0]] and genres[temp[0]]<2000):

                        genres[temp[0]]+=1
                        data_list.append(processItem(temp))
                except:
                    genres[temp[0]]=1
            line_num+=1
    print "**************************************************************************"
    print "No of songs: ",line_num-10
    print "**************************************************************************"

    print "Dataset composition:"
    for type in genres.keys():
        #print "\""+ type+"\",",
        print type,genres[type]
    print "**************************************************************************"
    print "Loading data in numpy arrays."
    t=time.time()
    np_data=np.array(data_list)
    print "Time elapsed:",time.time()-t,"secs."
    t=time.time()

preprocess()


**************************************************************************
No of songs:  59600
**************************************************************************
Dataset composition:
jazz and blues 2000
classic pop and rock 2000
classical 1874
punk 2000
metal 2000
pop 1617
dance and electronica 2000
hip-hop 434
soul and reggae 2000
folk 2000
**************************************************************************
Loading data in numpy arrays.
Time elapsed: 0.324131965637 secs.


### Feature and Labels Split 
Now, the data we just loaded contains both the feature and labels altogether. So, we need to seperate them out.
This is what we are doing in the next block of code. Just loaded data into features and labels.

In [15]:
def targetFeatureSplit( data ):
    """ 
        given a numpy array like the one returned from
        featureFormat, separate out the first feature
        and put it into its own list (this should be the 
        quantity you want to predict)

        return targets and features as separate lists

        (sklearn can generally handle both lists and numpy arrays as 
        input formats when training/predicting)
    """
    target = []
    features = []
    for item in data:
        target.append( item[0] )
        features.append( item[1:] )

    return target, features

target,features = targetFeatureSplit(data_list)

### Hot Encoding the Categorial Labels
Machine learning algorithms cannot work with categorical data directly. Categorical data must be 
converted to numbers so that computer can categorise them accordingly .So, we will encode all the labels using LabelEncoder and transform our labels to numerical encoding.

These can be inversed transform whenever required.

In [16]:
from sklearn.preprocessing import LabelEncoder

#label of the first song before encoding
print target[0]
enc = LabelEncoder()
target = enc.fit_transform(target)
#label of the song after LabelEncoding
print target[0]

classic pop and rock
0


### Preprocessing Data
Now, that we have properly encoded our labels. Next step, that we should take is feature scaling. We have 30 features, all these features have different ranges of value, this can cause different feature to have a different weight being used to fit the model.

To avoid this, we require to feature scale the values of all the features available to us so that all values come to certain range and feature weight is equally balanced.   

We need to feature scale all the features, we just extracted out of million song genre dataset using MinMaxScaler.

In [18]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
features=scaler.fit_transform(features)
#sample output
print features[0]

[ 0.71616261  0.5698089   0.14285714  0.36363636  0.          0.06578349
  0.70781667  0.30157788  0.54239591  0.51226928  0.34541314  0.43352076
  0.70267668  0.49087988  0.62865809  0.44089158  0.4746716   0.48106248
  0.07390126  0.03032639  0.10400228  0.03627104  0.03346692  0.07060975
  0.08077381  0.04852299  0.09597886  0.09277362  0.04458085  0.02255567]


### Loading Data in Numpy arrays for processing
Loading target and feature list to numpy arrays, so that can be processed by machine Learning algorithms properly.

__Note__:<br>
Numpy array expects data to be of one format, they don't expect strings, or NaN entries in them. We need to take care of these things while loading our inputs in numpy arrays.

In [19]:
features = np.array(features,dtype = np.float64)
print type(features)
print features[0]

<type 'numpy.ndarray'>
[ 0.71616261  0.5698089   0.14285714  0.36363636  0.          0.06578349
  0.70781667  0.30157788  0.54239591  0.51226928  0.34541314  0.43352076
  0.70267668  0.49087988  0.62865809  0.44089158  0.4746716   0.48106248
  0.07390126  0.03032639  0.10400228  0.03627104  0.03346692  0.07060975
  0.08077381  0.04852299  0.09597886  0.09277362  0.04458085  0.02255567]


### Train and Test split 
Now, that we have done preprocessing on our labels and features.
We need to split our input into training and testing set. Generally training and testing sets are in the ratio of __80:20__. <br>
We used train_test_split function to split our input into training and testing set.



In [20]:
def loadInput():
    print "Creating Training set and Test Set."
    print "-----------------------------------"
    print ""
    t=time.time()
    feature_train,feature_test,label_train,label_test = train_test_split(features, target, test_size=0.20, random_state=42)
    print "Time elapsed:",time.time()-t,"secs"
    print ""

    #size of train and test sets
    print "Size of training set:{} samples".format(len(feature_train))
    print "Size of testing set:{} samples".format(len(feature_test))
    
    print ""
    print ""
    return feature_train,feature_test,label_train,label_test

## Classification Algorithms and Genre Classification task.

We will be using different classification algorithms for this multiclass classification task of classifying
songs into different genres.
 

#### Evaluation Metrics
Generally people use accuracy score to evaluate the performance of a model. But this is a case of multiclass classification, accuracy metric doesn't make sense here since, the number of true positives of any class can 
vary, another reason of choosing F1-score as evaluation metric is number of data_points of each label can vary a
lot. So, F1-score is your best bet for evaluation metric.

### Training the Model
                          

### Naive Bayes Algorithm

We started with Naive Bayes Algorithm, reason being it is the simplest to code and understand algorithm.
We feed our data to Naive bayes model, the F1-sore it provides our lower bound performance benchmark.

In [23]:
from sklearn.naive_bayes import GaussianNB

feature_train,feature_test,label_train,label_test = loadInput()

clf_nb = GaussianNB()

t = time.time()
clf_nb.fit(feature_train,label_train)

pred_nb = clf_nb.predict(feature_test)

print "Time elapsed:",time.time()-t,"secs."
print "confusion_matrix:"
print ""
print(confusion_matrix(label_test,pred_nb))

print ""
print ""

print "classification_report:"
print classification_report(label_test,pred_nb)

print ""
print ""

print "Encoded Genres:" 
for index,genre in enumerate(enc.classes_):
    print genre,": ",index


Creating Training set and Test Set.
-----------------------------------

Time elapsed: 0.00357890129089 secs

Size of training set:14332 samples
Size of testing set:3583 samples


Time elapsed: 0.0134110450745 secs.
confusion_matrix:

[[ 54   8   7  76  17  17  49  78  37  44]
 [  9 273  14  24   5  13  13   4   5   2]
 [ 24  55  94  18  43  34  31  60  19  44]
 [ 31  15  11 162   1  21  22  76  33  31]
 [  1   0   5   1  27   1   1   8   5  29]
 [ 30  59  38  41   7 125  15  39  16  20]
 [  4   6  11   3   1   5 368   8  24   1]
 [ 15   3   4  45   6  11  37 136  24  31]
 [ 12   8   7  16  10  14 235  22  57  33]
 [ 27   2  12  34  30  10  10  83  13 163]]


classification_report:
             precision    recall  f1-score   support

          0       0.26      0.14      0.18       387
          1       0.64      0.75      0.69       362
          2       0.46      0.22      0.30       422
          3       0.39      0.40      0.39       403
          4       0.18      0.35      0.24 

#### Interim Observation

We get an F1-score of 41%.This becomes our lower bound.
Confusion Matrix above shows us all the false postives, true negetives, false negetives and true positives.

Now, the way to improve this F1-score we  move on to Support Vector Machine.

### Support  Vector Machine
After working out with Naive bayes Algorithm, we came to support vector machine beacause Non-linear SVM algorithms calculates boundaries that don't have to be a straight line. The benefit is that you can capture much more complex relationships between your datapoints without having to perform difficult transformations on your own. The downside is that the training time is much longer as it's much more computationally intensive.

So, Naivest SVC model with __'rbf'__ kernel gives us F1-Score of 43%.

As, stated SVM are computationally expensive, it took almost 3 times the time to train an SVM than a Naive Bayes Algorithm and still F1-score didn't go up by much. So, we need to look for other complex classification algorithms that can perform better on multiclass classification problem.

In [25]:


from sklearn.svm import SVC

feature_train,feature_test,label_train,label_test = loadInput()

t = time.time()

clf_svm = SVC()
clf_svm.fit(feature_train, label_train) 

pred_svm= clf_svm.predict(feature_test)

print "Time elapsed:",time.time()-t,"secs."

print "confusion_matrix:"
print ""
print(confusion_matrix(label_test,pred_svm))

print ""
print ""

print "classification_report:"
print classification_report(label_test,pred_svm)

print ""
print ""

print "Encoded Genres:" 
for index,genre in enumerate(enc.classes_):
    print genre,": ",index

 Creating Training set and Test Set.
-----------------------------------

Time elapsed: 0.00397300720215 secs

Size of training set:14332 samples
Size of testing set:3583 samples


Time elapsed: 28.6036570072 secs.
confusion_matrix:

[[ 89   9   8 109   0  26  25  22  34  65]
 [  9 285   9  23   0  11   9   7   4   5]
 [ 29  43 138  40   0  48  23  30  13  58]
 [ 59  10   3 202   0  33   2  35  26  33]
 [  1   0   9   4   0   1   3   4   2  54]
 [ 44  64  36  52   0 138   6  10   6  34]
 [ 14   5   8   8   0   3 328   7  55   3]
 [ 75   2   7  61   0   9  12  60  27  59]
 [ 22  12  11  21   0   6 121  20 153  48]
 [ 57   2  19  44   0  18   7  30  10 197]]


classification_report:
             precision    recall  f1-score   support

          0       0.22      0.23      0.23       387
          1       0.66      0.79      0.72       362
          2       0.56      0.33      0.41       422
          3       0.36      0.50      0.42       403
          4       0.00      0.00      0.00  

### K-Nearest Neighbour Algorithm
After Support Vector machine, we though of try something different. kNN is slow when you have a lot of observations, since it does not generalize over data in advance, it scans historical database each time a prediction is needed.

With kNN you need to think carefully about the distance measure. For instance, if one feature is measured in 1000s of kilometers, another feature in 0.001 grams, the first feature will dominate the distance measure. You can normalize the features, or give certain importance weights, based on the domain knowledge.

Also, in a very high dimensional space the distance to all neighbors becomes more or less the same, and the notion of nearest and far neighbors becomes blurred.

The simplest KNN model give us a F1-score of 41%, which comparable to our lower bound.So, we move on our next classification model.

In [26]:
from sklearn.neighbors import KNeighborsClassifier

t=time.time()
clf_knn = KNeighborsClassifier(n_neighbors=2)
clf_knn.fit(feature_train, label_train) 

pred_knn = clf_knn.predict(feature_test)

print "Time elapsed:",time.time()-t,"secs."

print "confusion_matrix:"
print ""
print(confusion_matrix(label_test,pred_knn))

print ""
print ""

print "classification_report:"
print classification_report(label_test,pred_knn)

print ""
print ""

print "Encoded Genres:" 
for index,genre in enumerate(enc.classes_):
    print genre,": ",index

Time elapsed: 1.03407907486 secs.
confusion_matrix:

[[193   7  21  68   3  32  14  26  14   9]
 [ 24 290  14  12   2   7   2   4   5   2]
 [ 75  49 146  45   9  33  21  28   7   9]
 [121  20  15 181   3  18   3  35   6   1]
 [ 15   5  11   9  16   2   1   8   5   6]
 [ 83  71  34  60   3  99  10  18   5   7]
 [ 29  10  15  21   2   3 318   8  24   1]
 [ 78  12  19  67   5  15  15  85   5  11]
 [ 63  15  30  35  11  12 100  26 108  14]
 [118   4  37  57  19  41   4  26  14  64]]


classification_report:
             precision    recall  f1-score   support

          0       0.24      0.50      0.33       387
          1       0.60      0.80      0.69       362
          2       0.43      0.35      0.38       422
          3       0.33      0.45      0.38       403
          4       0.22      0.21      0.21        78
          5       0.38      0.25      0.30       390
          6       0.65      0.74      0.69       431
          7       0.32      0.27      0.30       312
          8  

### Random Forest Algorithm, Benchmark Model
We finally came to Random Forest Algorithm, that has chosen as our benchmark model based on the reseach paper we are working with. The results in paper show that when value of n_estimators is set to/around 300 it gives the best
F1-Score.

Benchmark Model in the paper suggested it got a F1-Score of 58%. But We got consistent __60% F1-score__.
Though, we are working only on 1% of actual dataset, on which F1-score of 58% was achieved.

This improvement in the F1-Score can be because of:

    - The dataset composition is well balanced for genre categories.
    - Proper preprocessing done on data before fitting the model.
    


In [28]:

t=time.time()
feature_train,feature_test,label_train,label_test = loadInput()

clf_rf = RandomForestClassifier(min_samples_split=2,min_samples_leaf=1,n_estimators=300,class_weight="balanced")
clf_rf.fit(feature_train,label_train)

pred_rf = clf_rf.predict(feature_test)
print "Time elapsed:",time.time()-t,"secs."


print "confusion_matrix:"
print ""
print confusion_matrix(label_test,pred_rf)

print ""
print ""

print "classification_report:"
print classification_report(label_test,pred_rf)

print ""
print ""

print "Encoded Genres:" 
for index,genre in enumerate(enc.classes_):
    print genre,": ",index


Creating Training set and Test Set.
-----------------------------------

Time elapsed: 0.00345301628113 secs

Size of training set:14332 samples
Size of testing set:3583 samples


Time elapsed: 24.9928629398 secs.
confusion_matrix:

[[151   9  12  62   3  28  14  45  27  36]
 [  6 301  15  12   0  15   5   2   2   4]
 [ 11  21 253  17   3  41  11  18  14  33]
 [ 33   9   5 237   0  32   2  47  13  25]
 [  1   0  10   3  24   1   1   3   2  33]
 [ 28  35  35  29   1 221   2   8   6  25]
 [ 15   4   9   6   0   4 348   5  38   2]
 [ 34   0  17  46   2  12   6 154  10  31]
 [ 20   4  20  19   4  11  32  19 248  37]
 [ 44   2  22  28   1  21   0  38   4 224]]


classification_report:
             precision    recall  f1-score   support

          0       0.44      0.39      0.41       387
          1       0.78      0.83      0.81       362
          2       0.64      0.60      0.62       422
          3       0.52      0.59      0.55       403
          4       0.63      0.31      0.41   

### Interim Observations
Among the algorithms used above we see that Random Forest Algorithms give the highest F1-Score of 60%.
The next step that can be taken is:

  
    - Try ensemble methods to further optimise our model with RandomForestClassifier
    - Try to tune hyperparameters using GridSearchCV. 
    
    

## OnevsRest Classifier in sklearn.

Along with using ensemble methods for further optimising our model using GridSearchCV, we thought of using this with OnevsRestClassifiers. Also known as one-vs-all, this strategy consists in fitting one classifier per class. For each classifier, the class is fitted against all the other classes. In addition to its computational efficiency (only n_classes classifiers are needed), one advantage of this approach is its interpretability. Since each class is represented by one and one classifier only, it is possible to gain knowledge about the class by inspecting its corresponding classifier. This is the most commonly used strategy for multiclass classification and is a fair default choice.

After running our model through GridSearchCV we get optimisation values for the parameters.
    - min_samples_split = 2
    - min_samples_leaf = 2
    - n_estimators = 300
    
    

In [103]:
from sklearn.grid_search import GridSearchCV

feature_train,feature_test,label_train,label_test = loadInput()

def HPOptimizationGridSearch(feature_train,label_train):
    print "Fitting the classifier to the training set"
    param_grid = {
             'estimator__min_samples_split': range(2,10),
              'estimator__min_samples_leaf': range(2,10),
              'estimator__n_estimators': range(100,400)
              }
    clf = GridSearchCV(OneVsRestClassifier(RandomForestClassifier(n_jobs=-1)), param_grid)
    clf = clf.fit(feature_train,label_train)
    print "Best estimator found by grid search:"
    print clf.best_estimator_

    
#HPOptimizationGridSearch(feature_train,label_train)


Creating Training set and Test Set.
-----------------------------------

Time elapsed: 0.00197815895081 secs

Size of training set:14332 samples
Size of testing set:3583 samples


Fitting the classifier to the training set
Best estimator found by grid search:
OneVsRestClassifier(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          n_jobs=1)


### Training our model with Tuned Hyperparameters.
Now, that we have find out the tuned hyperparameters using GridSearchCV. We fit our model with input data using these hyperparameters.

We get a F1-score of 61% which is better than the benchmark model by 3% as mentioned in Reseach paper and 1% after we simulated the same model on our system.


In [31]:
t=time.time()

clf_OR=OneVsRestClassifier(RandomForestClassifier(min_samples_split=2,min_samples_leaf=1,n_estimators=300,class_weight="balanced"))

feature_train,feature_test,label_train,label_test = loadInput()

clf_OR.fit(feature_train,label_train)
pred_OR=clf_OR.predict(feature_test)
print "Time elapsed:",time.time()-t,"secs."

print "confusion_matrix:"
print ""
print confusion_matrix(label_test,pred_OR)

print ""
print ""

print "classification_report:"
print classification_report(label_test,pred_OR)

print ""
print ""

print "Encoded Genres:" 
for index,genre in enumerate(enc.classes_):
    print genre,": ",index


Creating Training set and Test Set.
-----------------------------------

Time elapsed: 0.00377821922302 secs

Size of training set:14332 samples
Size of testing set:3583 samples


Time elapsed: 174.244068861 secs.
confusion_matrix:

[[155  10  18  62   1  29  13  36  28  35]
 [  4 308  18   8   0  14   4   3   2   1]
 [ 18  19 275  12   2  35  11  12  12  26]
 [ 37  13   8 245   0  35   1  36  11  17]
 [  1   2  15   0  21   1   1   2   4  31]
 [ 17  38  43  28   1 224   4   8   6  21]
 [ 14   4  13   3   0   4 352   2  36   3]
 [ 28   3  23  45   1  14   5 155  10  28]
 [ 26   9  28  17   3   7  35   9 247  33]
 [ 38   3  32  24   1  19   2  39   6 220]]


classification_report:
             precision    recall  f1-score   support

          0       0.46      0.40      0.43       387
          1       0.75      0.85      0.80       362
          2       0.58      0.65      0.61       422
          3       0.55      0.61      0.58       403
          4       0.70      0.27      0.39   

## Totally Different Approach 

### Lyrical Analysis Model
In this Experimental approach, what we are trying to achieve is can we predict genre using the lyrics of the songs.
We are using requests and BeautifulSoup libraries to scrap the data out of the website.

In this approach we added code to download lyrics of the songs in the dataset that were available publicly from 
[LyricsWikia](http://lyrics.wikia.com/) 

We downloaded around 26000 song lyrics that are available from there and store them at dataset/finalLyrics.txt


In [106]:
import requests
from bs4 import BeautifulSoup, Comment, NavigableString
import sys, codecs, json


def getLyrics(singer, song):
    #Replace spaces with _

    singer = singer.replace(' ', '_')
    song = song.replace(' ', '_')
    r = requests.get('http://lyrics.wikia.com/{0}:{1}'.format(singer,song))
    
    s = BeautifulSoup(r.text,'lxml')
    #Get main lyrics holder
    lyrics = s.find("div",{'class':'lyricbox'})
    if lyrics is None:
        #raise ValueError("Song or Singer does not exist or the API does not have Lyrics")
        return None
    #Remove Scripts
    [s.extract() for s in lyrics('script')]

    #Remove Comments
    comments = lyrics.findAll(text=lambda text:isinstance(text, Comment))
    [comment.extract() for comment in comments]

    #Remove unecessary tags
    for tag in ['div','i','b','a']:
        for match in lyrics.findAll(tag):
            match.replaceWithChildren()
    #Get output as a string and remove non unicode characters and replace <br> with newlines
    lyrics= str(lyrics).replace('\n','').replace('<br/>',' ')
    output=lyrics[22:-6:]
    try:
        return output
    except:
        return output.encode('utf-8')


genres={}
lyrics_found=0
import codecs
y=codecs.open("dataset/finalLyrics.txt","w")
line_num=0
with codecs.open('dataset/msd_genre_dataset.txt','r') as f:
    for line in f:
        if line_num<=20:
            pass
        else:
            temp=line.split(',')
            lyrics=getLyrics(temp[2],temp[3])
            if(lyrics!=None):
                print temp[2],temp[3]
                if(lyrics.split(' ')[0]!='<span'):
                    try:
                        genres[temp[0]]+=1
                    except:
                        genres[temp[0]]=1
                    lyrics_found+=1
                    y.write(temp[0]+'**/**'+lyrics)
                    y.write('\n')
        line_num+=1
y.close()

######################################################

print"Downloading song completed from lyrics.wikia.com"


### Preprocessing the Lyrics
Now before we start working with our dataset, we again need to do some preprocessing over it.
As a song lyrics may contain punctuation marks and stopwords like it, she, me, him, in e.t.c. which give us 
no information about anything we removed them using nltk library.


In [111]:
from __future__ import division
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
import unicodedata
import codecs
import string
import pickle
stemmer = SnowballStemmer('english')
cachedStopWords = stopwords.words("english")

data=[]
## Processing the lyrics one by one, removing and special characters( and/or punctuation marks)
## and finally removing all the stop words that literallly give no information about genre.
with codecs.open('dataset/finalLyricsList.txt','r') as f:
    lines=f.readlines()
    count=0
    for line in lines:

        labels,features=line.split('**/**')
        features = unicode(features, "utf-8")
        features = unicodedata.normalize('NFKD',features).encode('ascii','ignore')
        features=features.translate(None, string.punctuation)
        features=features.lower()  
        features=[word for word in features.split() if word not in cachedStopWords]
        for word in features:
            stemmer.stem(word)
        features=" ".join(features)
        data.append([labels,features])
        count+=1
        if(count%500==0):
            print "completed:{} %.".format(count/len(lines)*100.0)

    genres={} 
    for line in lines:
        labels,features=line.split('**/**')
        try:
            genres[labels]+=1
        except:
            genres[labels]=0
    print "File composition"
    for g in genres.keys():
        print g+": ",genres[g]

#saving into serialized object
stem_data=open("dataset/stemmed_text",'wb')
pickle.dump(data,stem_data)
stem_data.close()





completed:2.02626033393 %.
completed:4.05252066786 %.
completed:6.07878100178 %.
completed:8.10504133571 %.
completed:10.1313016696 %.
completed:12.1575620036 %.
completed:14.1838223375 %.
completed:16.2100826714 %.
completed:18.2363430053 %.
completed:20.2626033393 %.
completed:22.2888636732 %.
completed:24.3151240071 %.
completed:26.3413843411 %.
completed:28.367644675 %.
completed:30.3939050089 %.
completed:32.4201653428 %.
completed:34.4464256768 %.
completed:36.4726860107 %.
completed:38.4989463446 %.
completed:40.5252066786 %.
completed:42.5514670125 %.
completed:44.5777273464 %.
completed:46.6039876803 %.
completed:48.6302480143 %.
completed:50.6565083482 %.
completed:52.6827686821 %.
completed:54.709029016 %.
completed:56.73528935 %.
completed:58.7615496839 %.
completed:60.7878100178 %.
completed:62.8140703518 %.
completed:64.8403306857 %.
completed:66.8665910196 %.
completed:68.8928513535 %.
completed:70.9191116875 %.
completed:72.9453720214 %.
completed:74.9716323553 %.
compl

### Using Bag of words 
We will be using bag of words strategy over the lyrics just downloaded and processed to classify songs into various genre categories. 

In this Bag of words strategy, what we are doing is using TfidfVectorizer and CountVectorizer, these to calculate the frequency of the words in the lyrics and also the inverse frequency of the word in the whole dataset and assign it an importance. Each word is assigned its importance.

Now, we feed this bag of words to Decision Tree, but two things to note is the decision tree overfits very easily. Plus a word can have multiple meaning related to it.So, will be taking a moderate size for min_samples_split parameter. 

And interestingly, we get a pretty decent F1-Score of 56% even without hypertuning anything. 



In [34]:
import pickle
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

#loading the stemmed lyrics
stem_data=open("dataset/stemmed_text","r")
data=pickle.load(stem_data)



def targetFeatureSplit( data ):
    """ 
        given a numpy array like the one returned from
        featureFormat, separate out the first feature
        and put it into its own list (this should be the 
        quantity you want to predict)

        return targets and features as separate lists

        (sklearn can generally handle both lists and numpy arrays as 
        input formats when training/predicting)
    """
    target = []
    features = []
    for item in data:
        target.append( item[0] )
        features.append( item[1] ) 
    return target, features


labels,features=targetFeatureSplit(data)



#label of the first song before encoding

enc = LabelEncoder()
target = enc.fit_transform(labels)


feature_train,feature_test,label_train,label_test = train_test_split(features, target, test_size=0.20, random_state=42)
vectorizer=TfidfVectorizer(sublinear_tf=True,max_df=0.5)
feature_train=vectorizer.fit_transform(feature_train)
feature_test=vectorizer.transform(feature_test).toarray()


from sklearn import tree
clf = tree.DecisionTreeClassifier(min_samples_split=23)
clf.fit(feature_train,label_train)
pred=clf.predict(feature_test)
importances = clf.feature_importances_

indices = np.argsort(importances)[::-1]
print ""
print ""
print 'Feature Ranking: '
for i in range(10):
    print "{} feature no.{} ({})".format(i+1,indices[i],importances[indices[i]])


print "Encoded Genres:" 
for index,genre in enumerate(enc.classes_):
    print genre,": ",index

print ""
print ""
print "confusion_matrix:"
print ""
print(confusion_matrix(label_test,pred))
print "classification report:"
print ""
print ""
print(classification_report(label_test,pred))





Feature Ranking: 
1 feature no.46889 (0.0420229633391)
2 feature no.35109 (0.0122767704976)
3 feature no.15472 (0.00917726504857)
4 feature no.41321 (0.00842699934753)
5 feature no.66007 (0.00829721995031)
6 feature no.61700 (0.00772061822435)
7 feature no.10807 (0.00740004225719)
8 feature no.32527 (0.00733699005256)
9 feature no.41128 (0.00680181903717)
10 feature no.14908 (0.00611062439899)
Encoded Genres:
classic pop and rock :  0
dance and electronica :  1
folk :  2
jazz and blues :  3
metal :  4
pop :  5
punk :  6
soul and reggae :  7


confusion_matrix:

[[1781   45  453   18   69   21   25   90]
 [  66   79   42    2    6    0    1    8]
 [ 505   23  476   16   26    8   12   32]
 [  59    2   24   16    1    0    3    5]
 [  97    9   54    1  107    2    3    8]
 [  42    4   23    1    3  113   17    3]
 [  67    6   41    2   10    7   64    2]
 [ 109   11   45    4   11    4    8  144]]
classification report:


             precision    recall  f1-score   support

      

# Results

Following conclusions can be drawn from the above observations:

    - Highest F1-score of 61% achieved using OnevsRestClassifier on RandomForestClassifier of ensemble methods.
    
    - Second experimental approach of lyrical analysis Model showed decent score with F1-Score of 56% 
      without hypertuning.
    

## Further Improvements

Although, there can be a lot of improvements to this project. Few improvements that come to my mind are:
    
1. Running the model over more data, original million song dataset with much more features.
2. Applying PCA on features and do dimensionality reduction to reduce computation time.
3. Use NLP and CNNs together to understand natural language and produce much better F1-Scores.